### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/go-wfs#1]
There needs to be some configuration of data providers, already running into inconsistency with id column names in gpkg feature tables.

Pull in & use tegola config handling?

**Comment by tomkralidis** [comment]
Another option is using the geocatalogo approach:

- https://github.com/go-spatial/geocatalogo/blob/master/geocatalogo-config.env
- https://github.com/go-spatial/geocatalogo/blob/master/geocatalogo-config.yml

**Comment by JivanAmara** [comment]
Took care of the blocking problem by adding an auto-config function to the GeoPackage provider which pulls all available features.  I'll leave this open, as people will want to tweak availability but it's much lower priority now.
