### ISSUE TITLE
HTML format for api link not supported.

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/go-wfs#105]
On the html root page, `http://localhost:9000/api?f=text/html` shouldn't be there, as the `/api/` endpoint only provides json.

**Comment by JivanAmara** [comment]
@tomkralidis Any clever ideas for dealing with this?

**Comment by JivanAmara** [comment]
I went with an html template conditional.

**Comment by tomkralidis** [comment]
Fair enough.  Proper support (future) could be a swagger UI response.

**Comment by JivanAmara** [comment]
I wouldn't want to bait people with a failing link.
