### ISSUE TITLE
Add tests for main.defaultGpkg()

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/go-wfs#41]

**Comment by jlucktay** [comment]
Hi, @JivanAmara I will have a shot at writing some test coverage for this.

Please feel free to assign it to me. Cheers!

**Comment by jlucktay** [comment]
PR #61 has been created. See what you think. Cheers! :)

**Comment by JivanAmara** [comment]
Hi James, we'll have to get you added to the repo in order to assign tickets to you, (@jj0hns0n ?).
I'll take a look probably Monday.  Thanks for your contribution, how did you come across the project & what's your interest in it?

**Comment by jlucktay** [comment]
Thanks @JivanAmara !

I came across the issue with [this search](https://github.com/search?l=Go&o=desc&q=label%3A%22good+first+issue%22+no%3Aassignee+&s=updated&state=open&type=Issues) for unassigned issues tagged with `good first issue`. 😅

I've been learning Go over the last couple of months and would like to put my new skills to some use, helping out where I can.
