### ISSUE TITLE
add properties to feature collection response

### ISSUE THREAD

**Issue by tomkralidis** [go-spatial/go-wfs#65]
Feature collection responses should have `numberMatched`, `numberReturned`, and `timeStamp` properties as per requirements 27/28/29.

**Comment by JivanAmara** [comment]
I couldn't find details in the spec re: `timeStamp`: https://github.com/opengeospatial/WFS_FES/blob/master/core/standard/clause_7_core.adoc

A timestamp could be interpreted as the time the query was initiated or when the data was last updated.  Without details, I don't think it makes sense to include it.
