### ISSUE TITLE
Add "text/html" links for each collection to collection metadata.

### ISSUE THREAD

**Issue by JivanAmara** [go-spatial/go-wfs#82]
w/ rel="alternate"
In:
* [x] links
* [x] collections/{collection}/links

**Comment by JivanAmara** [comment]
Hey Tom, this probably makes sense as a trailer to the html encoding stuff.

**Comment by tomkralidis** [comment]
+1 will cover in #72

**Comment by JivanAmara** [comment]
`collections/{collection}/links` link added but rel is "self" instead of "alternate"
